### ISSUE TITLE
I made v7 compatible version

### ISSUE THREAD

**Issue by KimuraYu45z** [bianjieai/nft-transfer#24]
please look at this issue.
https://github.com/cosmos/ibc-go/issues/3576

Can I serve my v7 compatible version?

**Comment by dreamer-zq** [comment]
> please look at this issue. [cosmos/ibc-go#3576](https://github.com/cosmos/ibc-go/issues/3576)
> 
> Can I serve my v7 compatible version?

The v7 version is already available, but it is still in the branch and has not been merged into the main branch，Please use https://github.com/bianjieai/nft-transfer/tree/dreamer/sdk-v0.47

**Comment by KimuraYu45z** [comment]
I see. thanks
